// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NavigationLink: typeof import('./src/components/NavigationLink.vue')['default']
    PageHeading: typeof import('./src/components/PageHeading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcon: typeof import('./src/components/SocialIcon.vue')['default']
  }

}
