// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    LoginFrom: typeof import('./src/components/LoginFrom.vue')['default']
    LoginIcon: typeof import('./src/components/LoginIcon.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageHeading: typeof import('./src/components/PageHeading.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallTextUnderForm: typeof import('./src/components/smallTextUnderForm.vue')['default']
    SocialIcon: typeof import('./src/components/SocialIcon.vue')['default']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
  }
}
