// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogPost: typeof import('./src/components/PostList.vue')['default']
    Comp: typeof import('./src/components/comp.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NavigationLink: typeof import('./src/components/NavigationLink.vue')['default']
    PageHeading: typeof import('./src/components/PageHeading.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcon: typeof import('./src/components/SocialIcon.vue')['default']
  }
}
